#
# MIT License
#
#  (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cray-rrs
  namespace: rack-resiliency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cray-rrs
  template:
    metadata:
      labels:
        app: cray-rrs
    spec:
      serviceAccountName: "cray-rrs-service"
      initContainers:
      - name: cray-rrs-init
        image: artifactory.algol60.net/csm-docker/unstable/cray-rrs/cray-rrs-init:1.0.0-20250514193421_cf72e6a
        #tag: latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
          - name: static_cm_name
            value: "rrs-mon-static"
          - name: dynamic_cm_name
            value: "rrs-mon-dynamic"
          - name: namespace
            value: "rack-resiliency"
        volumeMounts:
          - name: ssh-config
            mountPath: /etc/ssh
            readOnly: true
          - name: ssh-hostpath
            mountPath: /root/.ssh
            readOnly: true
      containers:
      - name: cray-rrs-rms
        image: artifactory.algol60.net/csm-docker/unstable/cray-rrs/cray-rrs-rms:1.0.0-20250514193421_cf72e6a
        #tag: latest
        imagePullPolicy: IfNotPresent
        env:
          - name: static_cm_name
            value: "rrs-mon-static"
          - name: dynamic_cm_name
            value: "rrs-mon-dynamic"
          - name: namespace
            value: "rack-resiliency"
          - name: key_criticalservice
            value: "critical-service-config.json"
          - name: key_zones
            value: "dynamic-data.yaml"
        volumeMounts:
          - name: ssh-config
            mountPath: /etc/ssh
            readOnly: true
          - name: ssh-hostpath
            mountPath: /root/.ssh
            readOnly: true
        ports:
        - containerPort: 8551
          name: http-rms
          protocol: TCP
        #livenessProbe:
        #  httpGet:
        #    path: /healthz/live
        #    port: http-rms
        #  initialDelaySeconds: 5
        #  periodSeconds: 180
        #  timeoutSeconds: 90
        #  failureThreshold: 5
        #  successThreshold: 1
        #readinessProbe:
        #  httpGet:
        #    path: /healthz/ready
        #    port: http-rms
        #  initialDelaySeconds: 5
        #  periodSeconds: 90
        #  timeoutSeconds: 90
        #  failureThreshold: 10
        #  successThreshold: 1
      - name: cray-rrs-api
        image: artifactory.algol60.net/csm-docker/unstable/cray-rrs/cray-rrs-api:1.0.0-20250514193421_cf72e6a
        #tag: latest
        imagePullPolicy: IfNotPresent
        env:
          - name: static_cm_name
            value: "rrs-mon-static"
          - name: dynamic_cm_name
            value: "rrs-mon-dynamic"
          - name: namespace
            value: "rack-resiliency"
          - name: key_criticalservice
            value: "critical-service-config.json"
          - name: key_zones
            value: "dynamic-data.yaml"
        volumeMounts:
          - name: ssh-config
            mountPath: /etc/ssh
            readOnly: true
          - name: ssh-hostpath
            mountPath: /root/.ssh
            readOnly: true
        ports:
        - containerPort: 8550
          name: http-api
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: http-api
          initialDelaySeconds: 5
          periodSeconds: 180
          timeoutSeconds: 90
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: http-api
          initialDelaySeconds: 5
          periodSeconds: 90
          timeoutSeconds: 90
          failureThreshold: 10
          successThreshold: 1
      volumes:
      - name: ssh-config
        hostPath:
          path: /etc/ssh
          type: Directory
      - name: ssh-hostpath
        hostPath:
          path: /root/.ssh
          type: Directory
