#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")
cray-service:
  type: Deployment
  nameOverride: cray-rrs
  #default replicaCount is 1, can be removed. Just keeping for readability.
  replicaCount: 1
  serviceAccountName: "cray-rrs-service"
  namespace: rack-resiliency
  strategy:
    type: Recreate
  initContainers:
    cray-rrs-init:
      name: cray-rrs-init
      image:
        repository: artifactory.algol60.net/csm-docker/unstable/cray-rrs/cray-rrs-init
    volumeMounts:
      - name: rrs-static-conf
        mountPath: /conf/rrs-static-conf
        readOnly: true
      - name: rrs-dynamic-conf
        mountPath: /conf/rrs-dynamic-conf
        readOnly: false
  containers:
    cray-rrs-rms:
      name: cray-rrs-rms
      image:
        repository: artifactory.algol60.net/csm-docker/unstable/cray-rrs/cray-rrs-rms
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
      livenessProbe:
        httpGet:
          path: /healthz
      readinessProbe:
        httpGet:
          path: /healthz
      volumeMounts:
        - name: rrs-static-conf
          mountPath: /conf/rrs-static-conf
          readOnly: true
        - name: rrs-dynamic-conf
          mountPath: /conf/rrs-dynamic-conf
          readOnly: false
    cray-rrs-api:
      name: cray-rrs-api
      image:
        repository: artifactory.algol60.net/csm-docker/unstable/cray-rrs/cray-rrs-api
      volumes:
        sshConfigPath: /etc/ssh
        sshHpPath: /root/.ssh
        cephConfigName: ceph-admin-config
        criticalSvcConfigName: rrs-map
      auth:
        serviceAccount: cray-rrs-reader
        clusterRole: cray-rrs-role
        clusterRoleBinding: cray-rrs-rolebinding
      virtualservice:
        name: cray-rrs-vs
        prefix: /apis/rrs
 
  volumes:
    rrs-static-config:
      name: rrs-static-conf
      configMap:
        name: cm_static
    rrs-dynamic-config:
      name: rrs-dynamic-conf
      configMap:
        name: cm_dynamic

  service:
    name: cray-rrs
    # Enabled by default with type "ClusterIP", can be removed. Keeping it for readability.
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 80
        
  ingress:
    enabled: true
    prefix: /apis/rrs/
    uri: /
